/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TranslationValueService } from "../translationValue.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TranslationValueCreateInput } from "./TranslationValueCreateInput";
import { TranslationValue } from "./TranslationValue";
import { TranslationValueFindManyArgs } from "./TranslationValueFindManyArgs";
import { TranslationValueWhereUniqueInput } from "./TranslationValueWhereUniqueInput";
import { TranslationValueUpdateInput } from "./TranslationValueUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TranslationValueControllerBase {
  constructor(
    protected readonly service: TranslationValueService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TranslationValue })
  @nestAccessControl.UseRoles({
    resource: "TranslationValue",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTranslationValue(
    @common.Body() data: TranslationValueCreateInput
  ): Promise<TranslationValue> {
    return await this.service.createTranslationValue({
      data: {
        ...data,

        language: data.language
          ? {
              connect: data.language,
            }
          : undefined,

        translationKey: data.translationKey
          ? {
              connect: data.translationKey,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        language: {
          select: {
            id: true,
          },
        },

        translationKey: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TranslationValue] })
  @ApiNestedQuery(TranslationValueFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TranslationValue",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async translationValues(
    @common.Req() request: Request
  ): Promise<TranslationValue[]> {
    const args = plainToClass(TranslationValueFindManyArgs, request.query);
    return this.service.translationValues({
      ...args,
      select: {
        createdAt: true,
        id: true,

        language: {
          select: {
            id: true,
          },
        },

        translationKey: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TranslationValue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TranslationValue",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async translationValue(
    @common.Param() params: TranslationValueWhereUniqueInput
  ): Promise<TranslationValue | null> {
    const result = await this.service.translationValue({
      where: params,
      select: {
        createdAt: true,
        id: true,

        language: {
          select: {
            id: true,
          },
        },

        translationKey: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TranslationValue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TranslationValue",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTranslationValue(
    @common.Param() params: TranslationValueWhereUniqueInput,
    @common.Body() data: TranslationValueUpdateInput
  ): Promise<TranslationValue | null> {
    try {
      return await this.service.updateTranslationValue({
        where: params,
        data: {
          ...data,

          language: data.language
            ? {
                connect: data.language,
              }
            : undefined,

          translationKey: data.translationKey
            ? {
                connect: data.translationKey,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          language: {
            select: {
              id: true,
            },
          },

          translationKey: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TranslationValue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TranslationValue",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTranslationValue(
    @common.Param() params: TranslationValueWhereUniqueInput
  ): Promise<TranslationValue | null> {
    try {
      return await this.service.deleteTranslationValue({
        where: params,
        select: {
          createdAt: true,
          id: true,

          language: {
            select: {
              id: true,
            },
          },

          translationKey: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
